---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01-overview"
      label: "Welcome to Infinicorp"
      solveButton: false
    - name: "module-02-hcc-vulnerabilities"
      label: "Evaluate and remediate CVEs"
      solveButton: false
    - name: "module-03-hcc-compliance"
      label: "Evaluate regulatory compliance"
      solveButton: false
    - name: "module-04-satellite-advisor"
      label: "Lightspeed Advisor in Satellite"
      solveButton: false
    - name: "module-05-satellite-vulnerability"
      label: "Lightspeed Vulnerability in Satellite"
      solveButton: false
    - name: "module-06-recap"
      label: "Recap"

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
  - name: "satellite terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel-${guid}-1 terminal"
    url: /wetty_rhel-${guid}-1
  - name: "rhel-${guid}-2 terminal"
    url: /wetty_rhel-${guid}-2/ssh/root
